### ISSUE TITLE
Mod Browser "Not Found"

### ISSUE THREAD

**Issue by Duvent-mindustry** [genNAowl/Upgraded-Factories-Java#1]
to fix this bug please add a release with a jar on it in releases, most new java mods forget to do this, if this is fixed, alert me, thanks!

**Comment by genNAowl** [comment]
Hmm I forgot to say that this mod has not been completely ported yet, and I will not be releasing anything until it is. 

(Currently only 3 blocks are there, so don't even try to download it)
